{{ if ne .Values.env_variables.APP_ENV "ci" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "nops-k8s-agent.fullname" . }}-pvc-metrics-high
spec:
  schedule: "19 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          activeDeadlineSeconds: {{ .Values.env_variables.APP_NOPS_K8S_AGENT_TIMEOUT }}
          {{ if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "nops-k8s-agent.fullname" . }}
          {{ else }}
          serviceAccountName: default
          {{ end }}
          containers:
          - resources:
              limits:
                cpu: 500m
                memory: 5Gi
              requests:
                cpu: 500m
                memory: 5Gi
            name: {{ .Chart.Name }}
            env:
              - name: APP_APP_VERSION
                value: "{{ .Chart.AppVersion }}"
              - name: APP_CHART_VERSION
                value: "{{ .Chart.Version }}"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: nops-k8s-agent
                    key: aws_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: nops-k8s-agent
                    key: aws_secret_access_key
            envFrom:
              - configMapRef:
                  name: {{ .Chart.Name }}-configmap
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command: ["python", "manage.py", "dumptos3", "--module-to-collect", "pvc_metrics", "--start-date", "", "--end-date", ""]
          restartPolicy: Never
{{ end }}
