apiVersion: apps/v1
kind: Deployment
metadata:
  name: nops-k8s-agent
  labels:
    app: nops-k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nops-k8s-agent
  template:
    metadata:
      labels:
        app: nops-k8s-agent
    spec:
      serviceAccountName: {{ include "nops-k8s-agent.serviceAccountName" . }}
      containers:
      - name: nops-k8s-agent
        env:
          - name: APP_APP_VERSION
            value: "{{ .Chart.AppVersion }}"
          - name: APP_CHART_VERSION
            value: "{{ .Chart.Version }}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: nops-k8s-agent
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: nops-k8s-agent
                key: aws_secret_access_key
        envFrom:
        - configMapRef:
              name: {{ .Chart.Name }}-configmap
        image: "ghcr.io/nops-io/nops-k8s-agent:master"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        command: ["sleep", "9999999999"]
