default:
  PROMETHEUS_SERVER_ENDPOINT: "http://prometheus-server.nops-k8s-agent.svc.cluster.local:9090"
  AWS_S3_BUCKET: ""
  AWS_S3_PREFIX: ""
  NOPS_K8S_AGENT_CLUSTER_ARN: ""
  NOPS_K8S_AGENT_PROM_TOKEN: ""
  APP_VERSION: ""
  CHART_VERSION: ""
  DEBUG: False
