default:
  PROMETHEUS_SERVER_ENDPOINT: "http://prometheus-server.nops-k8s-agent.svc.cluster.local:9090"
  NOPS_K8S_AGENT_CLUSTER_ID: ""
  NOPS_K8S_COLLECTOR_HOST: ""
  NOPS_K8S_COLLECTOR_PORT: ""
  NOPS_K8S_COLLECTOR_NO_SSL: ""
  NOPS_K8S_COLLECTOR_SKIP_SSL_VALIDATION: ""
  NOPS_K8S_COLLECTOR_API_KEY: ""
  NOPS_K8S_COLLECTOR_AWS_ACCOUNT_NUMBER: ""
  NOPS_K8S_AGENT_PROM_TOKEN: ""
